Repository CarsOk/SISMU-artesanias, pull requests merged in 2022-07, with the labels that each got.

#195 Se agregaron las validaciones y los botones eliminar en las vistas show
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/models/artesano.rb
  rails/SISMU/app/models/category.rb
  rails/SISMU/app/models/client.rb
  rails/SISMU/app/models/color.rb
  rails/SISMU/app/models/dproduction.rb
  rails/SISMU/app/models/empresa.rb
  rails/SISMU/app/models/production.rb
  rails/SISMU/app/models/producto.rb
  rails/SISMU/app/views/artesanos/_form.html.erb
  rails/SISMU/app/views/artesanos/edit.html.erb
  rails/SISMU/app/views/artesanos/show.html.erb
  rails/SISMU/app/views/clients/edit.html.erb
  rails/SISMU/app/views/clients/show.html.erb
  rails/SISMU/app/views/emfacturas/show.html.erb
  rails/SISMU/app/views/empresas/_form.html.erb
  rails/SISMU/app/views/empresas/edit.html.erb
  rails/SISMU/app/views/empresas/show.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productions/_form.html.erb
  rails/SISMU/app/views/productions/show.html.erb
  rails/SISMU/app/views/productos/edit.html.erb
Labels: back-end, front-end

#196 Mejora de vista index
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/db/schema.rb
Labels: front-end

#197 agregar alertas de eliminar
  documentacion/Documentación UML/Base de datos SISMUv01.xml
  documentacion/Documentación UML/Diagrama de clases SISMU.dia
  documentacion/Documentación UML/Diagrama de clases SISMU.dia.autosave
  documentacion/Documentación UML/Diagrama de clases SISMU.dia~
  documentacion/Documentación UML/Diagrama de clases SISMU.jpeg
  documentacion/Documentación UML/d.xml
  documentacion/Documentación UML/modello relacional.xml
  documentacion/Documentación UML/sq.png
  documentacion/Documentación UML/sql.png
  rails/SISMU/app/models/artesano.rb
  rails/SISMU/app/models/client.rb
  rails/SISMU/app/models/empresa.rb
  rails/SISMU/app/views/artesanos/_artesano.html.erb
  rails/SISMU/app/views/artesanos/show.html.erb
  rails/SISMU/app/views/categories/_category.html.erb
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/clients/show.html.erb
  rails/SISMU/app/views/colors/_color.html.erb
  rails/SISMU/app/views/emfacturas/_emfactura.html.erb
  rails/SISMU/app/views/emfacturas/show.html.erb
  rails/SISMU/app/views/empresas/_empresa.html.erb
  rails/SISMU/app/views/empresas/_form.html.erb
  rails/SISMU/app/views/empresas/show.html.erb
  rails/SISMU/app/views/facturas/_factura.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productions/_production.html.erb
  rails/SISMU/app/views/productions/show.html.erb
Labels: back-end

#200 Asteriscos de campos obligatorios agregado
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/views/artesanos/_form.html.erb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/empresas/_form.html.erb
  rails/SISMU/app/views/facturas/_form.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/productions/_form.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
Labels: front-end
