Repository CarsOk/SISMU-artesanias, pull requests merged in 2022-05, with the labels that each got.

#42 Modificaciones
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/views/devise/passwords/new.html.erb
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/config/routes.rb
Labels: enhancement, front-end

#43 Organizado los css
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/views/layouts/application.html.erb
Labels: enhancement, front-end

#44 NOTA
  documentacion/NOTAS DE LA EXPO1.txt
  rails/SISMU/app/views/home/index.html.erb
Labels: documentation

#53 modificado el devise en el registrar
  rails/SISMU/app/controllers/application_controller.rb
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/db/migrate/20220503040619_add_primer_nombre_to_users.rb
  rails/SISMU/db/schema.rb
Labels: back-end, front-end

#56 Creado direccionamientos
  flutter/sismu_application/pubspec.lock
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/index.html.erb
  rails/SISMU/app/views/productos/new.html.erb
Labels: enhancement, front-end

#59 crear render de los productos creados
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
  rails/SISMU/app/views/productos/show.html.erb
  rails/SISMU/config/routes.rb
Labels: back-end

#63 Subir imagen en los productos
  rails/SISMU/Gemfile
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/models/producto.rb
  rails/SISMU/app/uploaders/avatar_uploader.rb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
  rails/SISMU/config/application.rb
  rails/SISMU/db/migrate/20220504220218_add_avatar_to_productos.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/public/uploads/producto/avatar/2/Atrapa-Sueno-entre-sueno-rojo-negro-13-diametro-regalo-lima-peru-delivery.jpg
  rails/SISMU/public/uploads/producto/avatar/4/UseCaseDiagram1.jpg
Labels: back-end

#64 Arreglado los estilos del login
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/views/devise/passwords/new.html.erb
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/app/views/devise/sessions/new.html.erb
Labels: enhancement, front-end

#65 agregar tabla materials y relación con prductos
  rails/SISMU/app/controllers/materials_controller.rb
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/helpers/materials_helper.rb
  rails/SISMU/app/models/material.rb
  rails/SISMU/app/models/producto.rb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/materials/_form.html.erb
  rails/SISMU/app/views/materials/_material.html.erb
  rails/SISMU/app/views/materials/edit.html.erb
  rails/SISMU/app/views/materials/index.html.erb
  rails/SISMU/app/views/materials/new.html.erb
  rails/SISMU/app/views/materials/show.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/_show.html.erb
  rails/SISMU/app/views/productos/show.html.erb
  rails/SISMU/config/application.rb
  rails/SISMU/config/routes.rb
  rails/SISMU/db/migrate/20220506193316_create_materials.rb
  rails/SISMU/db/migrate/20220506194647_create_join_tables_materials_productos.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/test/controllers/materials_controller_test.rb
  rails/SISMU/test/fixtures/materials.yml
  rails/SISMU/test/models/material_test.rb
Labels: back-end

#66 agregar iconos al link_to
  rails/SISMU/app/views/layouts/application.html.erb
Labels: back-end, front-end

#67 vista de ultmimos productos añadidos
  rails/SISMU/app/controllers/home_controller.rb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/public/uploads/producto/avatar/5/rBVaI1i2yo6AP1jFAAjOp19ZFGw777.jpg
Labels: back-end, front-end

#69 Arreglo del icono lateral
  rails/SISMU/app/assets/images/minilogo_lateral_sandra_munoz_artesanias.png
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/views/layouts/application.html.erb
Labels: front-end

#68 tabla de productos
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: front-end

#71 Eliminación de la base de datos
  rails/SISMU/app/controllers/home_controller.rb
  rails/SISMU/app/models/category.rb
  rails/SISMU/app/models/material.rb
  rails/SISMU/app/models/producto.rb
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/db/migrate/20220425205837_create_productos.rb
  rails/SISMU/db/migrate/20220425211622_create_categories.rb
  rails/SISMU/db/migrate/20220427195808_create_join_table_categories_productos.rb
  rails/SISMU/db/migrate/20220503040619_add_primer_nombre_to_users.rb
  rails/SISMU/db/migrate/20220504220218_add_avatar_to_productos.rb
  rails/SISMU/db/migrate/20220506193316_create_materials.rb
  rails/SISMU/db/migrate/20220506194647_create_join_tables_materials_productos.rb
  rails/SISMU/db/schema.rb
Labels: back-end, remove

#76 corregir back_end
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/models/category.rb
  rails/SISMU/app/models/material.rb
  rails/SISMU/app/models/producto.rb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/db/migrate/20220425211622_create_categories.rb
  rails/SISMU/db/migrate/20220504220218_add_avatar_to_productos.rb
  rails/SISMU/db/migrate/20220506193316_create_materials.rb
  rails/SISMU/db/migrate/20220506194647_create_join_tables_materials_productos.rb
  rails/SISMU/db/migrate/20220511222152_create_productos.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/test/fixtures/categories.yml
  rails/SISMU/test/fixtures/materials.yml
  rails/SISMU/test/fixtures/productos.yml
  rails/SISMU/test/models/category_test.rb
  rails/SISMU/test/models/material_test.rb
Labels: back-end

#77 agregando tabla categories y relacion
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/models/category.rb
  rails/SISMU/app/models/producto.rb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
  rails/SISMU/db/migrate/20220513032906_create_categories.rb
  rails/SISMU/db/migrate/20220513035705_create_join_table_categories_productos.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/test/fixtures/categories.yml
  rails/SISMU/test/models/category_test.rb
Labels: back-end

#83 agregar campo color
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/colors_controller.rb
  rails/SISMU/app/controllers/facturas/detalles_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/helpers/colors_helper.rb
  rails/SISMU/app/models/client.rb
  rails/SISMU/app/models/color.rb
  rails/SISMU/app/models/detalle.rb
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/colors/create.html.erb
  rails/SISMU/app/views/colors/index.html.erb
  rails/SISMU/app/views/colors/new.html.erb
  rails/SISMU/app/views/colors/show.html.erb
  rails/SISMU/app/views/facturas/_form.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/config/routes.rb
  rails/SISMU/db/migrate/20220511222152_create_productos.rb
  rails/SISMU/db/migrate/20220513200332_create_clients.rb
  rails/SISMU/db/migrate/20220516200221_create_facturas.rb
  rails/SISMU/db/migrate/20220516200409_create_detalles.rb
  rails/SISMU/db/migrate/20220521165510_create_colors.rb
  rails/SISMU/db/migrate/20220521165804_create_join_table_colors_detalless.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/test/controllers/colors_controller_test.rb
  rails/SISMU/test/fixtures/colors.yml
  rails/SISMU/test/models/color_test.rb
Labels: back-end, front-end

#85 agregado el eliminar y editar a las vistas
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/facturas/detalles_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/clients/edit.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/facturas/_factura.html.erb
  rails/SISMU/app/views/facturas/edit.html.erb
  rails/SISMU/app/views/facturas/index.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/edit.html.erb
  rails/SISMU/config/routes.rb
Labels: back-end

#87 agregue link de cliente en el menu porque no estaba
  rails/SISMU/app/views/layouts/application.html.erb
Labels: back-end
