Repository CarsOk/SISMU-artesanias, pull requests merged in 2022-06, with the labels that each got.

#91 Creación del perfíl de usuario y contador
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/controllers/profiles_controller.rb
  rails/SISMU/app/helpers/profiles_helper.rb
  rails/SISMU/app/models/profile.rb
  rails/SISMU/app/models/user.rb
  rails/SISMU/app/uploaders/foto_uploader.rb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/profiles/edit.html.erb
  rails/SISMU/app/views/profiles/show.html.erb
  rails/SISMU/config/routes.rb
  rails/SISMU/db/migrate/20220601194030_create_profiles.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/test/controllers/profiles_controller_test.rb
  rails/SISMU/test/fixtures/profiles.yml
  rails/SISMU/test/models/profile_test.rb
Labels: back-end

#95 boton eliminar en los modelos
  rails/SISMU/app/controllers/facturas/detalles_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/facturas/_factura.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
Labels: back-end

#96 Mejora de la vista formulario y correcciones generales
  rails/SISMU/app/assets/images/iconos/artesanos.png
  rails/SISMU/app/assets/images/iconos/producto.png
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
Labels: front-end

#97 mejora de vistas new cliente, factura, productos
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/factura.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/facturas/_form.html.erb
  rails/SISMU/app/views/facturas/new.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
Labels: front-end

#98 agregar eliminar
  documentacion/Documentación UML/Diagrama de clases SISMU.dia
  documentacion/Documentación UML/Diagrama de clases SISMU.dia~
  documentacion/Documentación UML/Diagrama de clases SISMU.jpeg
  documentacion/Documentación UML/sq.png
  rails/SISMU/Gemfile
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/productions/dproductions_controller.rb
  rails/SISMU/app/controllers/productions_controller.rb
  rails/SISMU/app/models/artesano.rb
  rails/SISMU/app/views/artesanos/_artesano.html.erb
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/facturas/_factura.html.erb
  rails/SISMU/app/views/facturas/index.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productions/_production.html.erb
  rails/SISMU/app/views/productions/index.html.erb
  rails/SISMU/app/views/productions/show.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
Labels: back-end, front-end

#102 Implementado nuevo diseño en las cartas dentro de la pagina de documentación
  documentacion/Pagina Documentacion/css/style.css
  documentacion/Pagina Documentacion/index.html
  documentacion/Pagina Documentacion/modelo.html
  rails/SISMU/db/schema.rb
Labels: documentation, front-end

#105 Primeras vistas de index terminadas
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/artesanos/_artesano.html.erb
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/clients/show.html.erb
  rails/SISMU/app/views/emfacturas/_emfactura.html.erb
  rails/SISMU/app/views/emfacturas/index.html.erb
  rails/SISMU/app/views/empresas/_empresa.html.erb
  rails/SISMU/app/views/empresas/index.html.erb
  rails/SISMU/app/views/empresas/show.html.erb
  rails/SISMU/app/views/facturas/_factura.html.erb
  rails/SISMU/app/views/facturas/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productions/_production.html.erb
  rails/SISMU/app/views/productions/index.html.erb
  rails/SISMU/app/views/productions/show.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
  rails/SISMU/app/views/productos/show.html.erb
  rails/SISMU/db/schema.rb
Labels: front-end

#106 agregar schema faltantes
  rails/SISMU/db/migrate/20220607022920_create_join_table_colors_emdetalles.rb
  rails/SISMU/db/schema.rb
Labels: back-end

#115 estilos en las vistas de formulario
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/factura.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/artesanos/_form.html.erb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
Labels: front-end

#114 Mejora en las vistas NEW
  rails/SISMU/app/assets/images/iconos/construccion.png
  rails/SISMU/app/assets/images/iconos/empresa.png
  rails/SISMU/app/assets/images/iconos/empresa_disabled.png
  rails/SISMU/app/assets/images/iconos/empresa_new.png
  rails/SISMU/app/assets/images/iconos/factura.png
  rails/SISMU/app/assets/images/iconos/inventario.png
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/empresas/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_show.html.erb
  rails/SISMU/app/views/productos/show.html.erb
Labels: front-end

#116 diagrmas
  documentacion/Documentación UML/Base de datos SISMUv01.xml
  documentacion/Documentación UML/Diagrama de clases SISMU.dia
  documentacion/Documentación UML/Diagrama de clases SISMU.dia~
  documentacion/Documentación UML/Diagrama de clases SISMU.jpeg
  documentacion/Documentación UML/modello relacional.xml
  documentacion/Documentación UML/sql.png
  rails/SISMU/app/controllers/materials_controller.rb
  rails/SISMU/app/helpers/materials_helper.rb
  rails/SISMU/app/views/materials/_form.html.erb
  rails/SISMU/app/views/materials/_material.html.erb
  rails/SISMU/app/views/materials/edit.html.erb
  rails/SISMU/app/views/materials/index.html.erb
  rails/SISMU/app/views/materials/new.html.erb
  rails/SISMU/app/views/materials/show.html.erb
  rails/SISMU/test/controllers/materials_controller_test.rb
Labels: documentation

#117 cambios id
  rails/SISMU/app/models/artesano.rb
  rails/SISMU/app/models/client.rb
  rails/SISMU/app/models/empresa.rb
  rails/SISMU/app/models/factura.rb
  rails/SISMU/app/models/production.rb
  rails/SISMU/app/models/producto.rb
Labels: back-end

#118 Perfil
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/show.html.erb
  rails/SISMU/app/views/profiles/index.html.erb
Labels: front-end

#119 Se agrego foto de perfil para los usuarios
  rails/SISMU/app/controllers/artesanos_controller.rb
  rails/SISMU/app/controllers/categories_controller.rb
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/emfacturas/emdetalles_controller.rb
  rails/SISMU/app/controllers/emfacturas_controller.rb
  rails/SISMU/app/controllers/empresas_controller.rb
  rails/SISMU/app/controllers/facturas/detalles_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/materials_controller.rb
  rails/SISMU/app/controllers/productions/dproductions_controller.rb
  rails/SISMU/app/controllers/productions_controller.rb
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/controllers/profiles_controller.rb
  rails/SISMU/app/models/artesano.rb
  rails/SISMU/app/models/profile.rb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/profiles/edit.html.erb
  rails/SISMU/app/views/profiles/index.html.erb
  rails/SISMU/app/views/profiles/show.html.erb
  rails/SISMU/db/migrate/20220613214853_add_avatar_to_profiles.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/public/uploads/profile/avatar/1/dragon.png
Labels: back-end

#120 Adelantos en el nuevo diseño del LOGIN
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/app/views/devise/sessions/new.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/layouts/devise.html.erb
Labels: front-end

#123 crear alertas de validaciones
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/controllers/artesanos_controller.rb
  rails/SISMU/app/models/artesano.rb
  rails/SISMU/app/models/client.rb
  rails/SISMU/app/models/detalle.rb
  rails/SISMU/app/models/emdetalle.rb
  rails/SISMU/app/models/emfactura.rb
  rails/SISMU/app/models/empresa.rb
  rails/SISMU/app/models/factura.rb
  rails/SISMU/app/models/production.rb
  rails/SISMU/app/models/producto.rb
  rails/SISMU/app/views/artesanos/_form.html.erb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/clients/update.html.erb
  rails/SISMU/app/views/colors/create.html.erb
  rails/SISMU/app/views/emfacturas/_form.html.erb
  rails/SISMU/app/views/empresas/_form.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productions/_form.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/update.html.erb
Labels: back-end, front-end

#127 adelantos en la pagina de documentación
  documentacion/Pagina Documentacion/css/style.css
  documentacion/Pagina Documentacion/diagramas.html
  documentacion/Pagina Documentacion/images/Modelo.jpg
  documentacion/Pagina Documentacion/images/diagramaClase.jpg
  documentacion/Pagina Documentacion/images/diagramaObjetos.jpg
  documentacion/Pagina Documentacion/images/modelo.png
  documentacion/Pagina Documentacion/modelo.html
Labels: documentation, front-end

#128 Mejora en vista formulario y grid en home responsive
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/devise/passwords/new.html.erb
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/app/views/devise/sessions/new.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
Labels: front-end

#129 agregado buscador
  rails/SISMU/app/controllers/artesanos_controller.rb
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/emfacturas_controller.rb
  rails/SISMU/app/controllers/empresas_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/productions_controller.rb
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/emfacturas/index.html.erb
  rails/SISMU/app/views/empresas/index.html.erb
  rails/SISMU/app/views/facturas/index.html.erb
  rails/SISMU/app/views/productions/index.html.erb
Labels: front-end

#130 Mejora en vista formulario y grid en home responsive
  rails/SISMU/app/assets/images/iconos/ajuste_blanco.png
  rails/SISMU/app/assets/images/iconos/canasta_blanco.png
  rails/SISMU/app/assets/images/iconos/edificio.png
  rails/SISMU/app/assets/images/iconos/factura_gris.png
  rails/SISMU/app/assets/images/iconos/home_blanco.png
  rails/SISMU/app/assets/images/iconos/informacion_blanco.png
  rails/SISMU/app/assets/images/iconos/manos.png
  rails/SISMU/app/assets/images/iconos/recibo_blanco.png
  rails/SISMU/app/assets/images/iconos/usuario_blanco.png
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/assets/stylesheets/productions.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/models/client.rb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productions/_form.html.erb
  rails/SISMU/config/routes.rb
Labels: documentation, front-end

#133 modificacion de formulario produccion y artesanos
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/empresa.css
  rails/SISMU/app/models/production.rb
  rails/SISMU/app/views/artesanos/_form.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/productions/_form.html.erb
Labels: front-end

#134 diseño
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/controllers/home_controller.rb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/public/uploads/profile/avatar/1/default_profile.jpg
Labels: front-end

#135 Arreglo en titulos
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/profiles/index.html.erb
Labels: front-end

#139 Se agrego el logo en el formulario del iniciar sesion
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/views/devise/sessions/new.html.erb
Labels: front-end

#140 Perfil
  rails/SISMU/Gemfile
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/controllers/application_controller.rb
  rails/SISMU/app/models/user.rb
  rails/SISMU/app/views/devise/registrations/edit.html.erb
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/db/migrate/20220622052538_create_active_storage_tables.active_storage.rb
  rails/SISMU/db/schema.rb
Labels: front-end

#141 Media query
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/layouts/application.html.erb
Labels: front-end

#145 perfil maquetado
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/index.css
  rails/SISMU/app/assets/stylesheets/perfil.css
  rails/SISMU/app/views/devise/registrations/edit.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
Labels: front-end

#147 Arreglada la funcionalidad del perfil
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/views/devise/registrations/edit.html.erb
Labels: front-end

#148 Nuevo diseño de las tablas y botones
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: front-end

#149 vista de perfil mejorado
  rails/SISMU/app/assets/stylesheets/perfil.css
  rails/SISMU/app/views/devise/registrations/edit.html.erb
Labels: front-end

#150 index de formulario responsive
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: front-end

#151 avances tablas
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/clients/show.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: front-end

#154 Adelantos en las tablas y correcciones de conflictos
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/productions.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/artesanos/_artesano.html.erb
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/artesanos/show.html.erb
  rails/SISMU/app/views/clients/_client.html.erb
  rails/SISMU/app/views/clients/show.html.erb
  rails/SISMU/app/views/productions/_production.html.erb
  rails/SISMU/app/views/productions/index.html.erb
  rails/SISMU/app/views/productions/show.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: front-end

#155 Avances en el diseño de las tablas
  rails/SISMU/Gemfile
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/controllers/artesanos_controller.rb
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/emfacturas_controller.rb
  rails/SISMU/app/controllers/empresas_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/productions_controller.rb
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/views/facturas/_factura.html.erb
  rails/SISMU/app/views/facturas/index.html.erb
Labels: front-end

#156 Terminadas todas las tablas en las vistas index
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/empresa.css
  rails/SISMU/app/assets/stylesheets/productions.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/artesanos/_artesano.html.erb
  rails/SISMU/app/views/emfacturas/_emfactura.html.erb
  rails/SISMU/app/views/emfacturas/index.html.erb
  rails/SISMU/app/views/empresas/_empresa.html.erb
  rails/SISMU/app/views/empresas/index.html.erb
  rails/SISMU/app/views/facturas/_factura.html.erb
  rails/SISMU/app/views/productions/_production.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: front-end

#158 Adelantos en el nuevo modelo de las vistas shows
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/views/clients/show.html.erb
Labels: front-end

#157 acomodado el buscar de las paginas, index de las tablas responsive, e…
  rails/SISMU/app/assets/images/iconos/usuarios_blanco.png
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/empre_factura.css
  rails/SISMU/app/assets/stylesheets/empresa.css
  rails/SISMU/app/assets/stylesheets/productions.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/devise/registrations/edit.html.erb
  rails/SISMU/app/views/emfacturas/index.html.erb
  rails/SISMU/app/views/empresas/index.html.erb
  rails/SISMU/app/views/facturas/index.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productions/index.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: front-end

#160 agregar filtro
  rails/SISMU/Gemfile
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/_search_form.html.erb
  rails/SISMU/app/views/productos/index.html.erb
Labels: back-end, front-end

#162 agregado campos de correo y ciudad en la tabla de empresas
  rails/SISMU/app/controllers/empresas_controller.rb
  rails/SISMU/app/views/empresas/_empresa.html.erb
  rails/SISMU/app/views/empresas/_form.html.erb
  rails/SISMU/app/views/empresas/index.html.erb
  rails/SISMU/db/migrate/20220627195058_add_correo_to_empresa.rb
  rails/SISMU/db/schema.rb
Labels: back-end

#161 Avances en los shows
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/views/artesanos/show.html.erb
  rails/SISMU/app/views/clients/show.html.erb
  rails/SISMU/app/views/emfacturas/index.html.erb
Labels: front-end

#163 agregar filtros
  documentacion/Documentación UML/Diagrama de clases SISMU.dia
  documentacion/Documentación UML/Diagrama de clases SISMU.dia~
  documentacion/Documentación UML/Diagrama de clases SISMU.jpeg
  documentacion/Documentación UML/modello relacional.xml
  documentacion/Documentación UML/sq.png
  documentacion/Documentación UML/sql.png
  rails/SISMU/app/assets/stylesheets/alertas.css
  rails/SISMU/app/controllers/application_controller.rb
  rails/SISMU/app/controllers/artesanos_controller.rb
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/emfacturas/emdetalles_controller.rb
  rails/SISMU/app/controllers/emfacturas_controller.rb
  rails/SISMU/app/controllers/empresas_controller.rb
  rails/SISMU/app/controllers/facturas/detalles_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/productions_controller.rb
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/models/detalle.rb
  rails/SISMU/app/policies/application_policy.rb
  rails/SISMU/app/policies/artesano_policy.rb
  rails/SISMU/app/policies/client_policy.rb
  rails/SISMU/app/policies/emfactura_policy.rb
  rails/SISMU/app/policies/empresa_policy.rb
  rails/SISMU/app/policies/factura_policy.rb
  rails/SISMU/app/policies/production_policy.rb
  rails/SISMU/app/policies/producto_policy.rb
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/emfacturas/_emfactura.html.erb
  rails/SISMU/app/views/emfacturas/index.html.erb
  rails/SISMU/app/views/emfacturas/show.html.erb
  rails/SISMU/app/views/empresas/index.html.erb
  rails/SISMU/app/views/facturas/index.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/productions/index.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/_producto.html.erb
  rails/SISMU/app/views/productos/index.html.erb
  rails/SISMU/test/policies/artesano_policy_test.rb
  rails/SISMU/test/policies/client_policy_test.rb
  rails/SISMU/test/policies/emfactura_policy_test.rb
  rails/SISMU/test/policies/empresa_policy_test.rb
  rails/SISMU/test/policies/factura_policy_test.rb
  rails/SISMU/test/policies/production_policy_test.rb
  rails/SISMU/test/policies/producto_policy_test.rb
Labels: back-end, front-end

#165 Mejora de estilos en devise, color, categoria, login
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/configs.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/perfil.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/javascript/application.js
  rails/SISMU/app/views/categories/index.html.erb
  rails/SISMU/app/views/colors/index.html.erb
  rails/SISMU/app/views/configs/index.html.erb
  rails/SISMU/app/views/devise/registrations/edit.html.erb
  rails/SISMU/app/views/devise/registrations/new.html.erb
  rails/SISMU/app/views/devise/sessions/new.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
Labels: front-end

#164 Se agregaron nuevos estilos en las vistas edit y new
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/empre_factura.css
  rails/SISMU/app/assets/stylesheets/empresa.css
  rails/SISMU/app/assets/stylesheets/factura.css
  rails/SISMU/app/assets/stylesheets/productions.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/controllers/artesanos_controller.rb
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/emfacturas_controller.rb
  rails/SISMU/app/controllers/empresas_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/productions_controller.rb
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/views/artesanos/_form.html.erb
  rails/SISMU/app/views/artesanos/edit.html.erb
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/clients/edit.html.erb
  rails/SISMU/app/views/emfacturas/_form.html.erb
  rails/SISMU/app/views/empresas/_empresa.html.erb
  rails/SISMU/app/views/empresas/_form.html.erb
  rails/SISMU/app/views/empresas/edit.html.erb
  rails/SISMU/app/views/empresas/show.html.erb
  rails/SISMU/app/views/facturas/_form.html.erb
  rails/SISMU/app/views/facturas/new.html.erb
  rails/SISMU/app/views/productions/_form.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
  rails/SISMU/app/views/productos/edit.html.erb
  rails/SISMU/app/views/productos/new.html.erb
Labels: front-end

#167 ajuustes de posicion en la vista de producto y cambio del nombre en e…
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/empresa.css
  rails/SISMU/app/views/empresas/_form.html.erb
  rails/SISMU/app/views/empresas/edit.html.erb
  rails/SISMU/app/views/productos/_form.html.erb
Labels: front-end

#168 Acomodado en los container el show de factura
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
Labels: front-end

#170 Estilos de facturas
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/configs.css
  rails/SISMU/app/assets/stylesheets/factura.css
  rails/SISMU/app/views/artesanos/index.html.erb
  rails/SISMU/app/views/clients/index.html.erb
  rails/SISMU/app/views/emfacturas/index.html.erb
  rails/SISMU/app/views/emfacturas/show.html.erb
  rails/SISMU/app/views/facturas/show.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/layouts/application.html.erb
  rails/SISMU/app/views/productions/show.html.erb
  rails/SISMU/config/application.rb
  rails/SISMU/config/locales/devise.en.yml
  rails/SISMU/config/locales/devise.es.yml
Labels: front-end

#172 Revert "cambios"
  rails/SISMU/Gemfile
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/controllers/artesanos_controller.rb
  rails/SISMU/app/controllers/categories_controller.rb
  rails/SISMU/app/controllers/clients_controller.rb
  rails/SISMU/app/controllers/emfacturas_controller.rb
  rails/SISMU/app/controllers/empresas_controller.rb
  rails/SISMU/app/controllers/facturas_controller.rb
  rails/SISMU/app/controllers/productions_controller.rb
  rails/SISMU/app/controllers/productos_controller.rb
  rails/SISMU/app/views/layouts/application.html.erb
Labels: back-end

#173 traduccion del devise
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/config/application.rb
  rails/SISMU/config/locales/devise.es.yml
Labels: back-end

#189 eliminar profile
  rails/SISMU/app/controllers/profiles_controller.rb
  rails/SISMU/app/helpers/profiles_helper.rb
  rails/SISMU/app/models/profile.rb
  rails/SISMU/app/views/profiles/edit.html.erb
  rails/SISMU/app/views/profiles/index.html.erb
  rails/SISMU/app/views/profiles/show.html.erb
  rails/SISMU/db/migrate/20220601194030_create_profiles.rb
  rails/SISMU/db/migrate/20220613214853_add_avatar_to_profiles.rb
  rails/SISMU/db/schema.rb
  rails/SISMU/test/controllers/profiles_controller_test.rb
  rails/SISMU/test/fixtures/profiles.yml
  rails/SISMU/test/models/profile_test.rb
Labels: back-end

#187 se modifico los estilos de los formulario categoria y las alertas
  rails/SISMU/Gemfile
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/devise.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/views/categories/_form.html.erb
  rails/SISMU/app/views/colors/_form.html.erb
  rails/SISMU/config/application.rb
  rails/SISMU/config/locales/devise.es.yml
Labels: front-end

#188 Correcciones generales
  rails/SISMU/Gemfile
  rails/SISMU/Gemfile.lock
  rails/SISMU/app/assets/stylesheets/application.css
  rails/SISMU/app/assets/stylesheets/artesano.css
  rails/SISMU/app/assets/stylesheets/clientes.css
  rails/SISMU/app/assets/stylesheets/empresa.css
  rails/SISMU/app/assets/stylesheets/factura.css
  rails/SISMU/app/assets/stylesheets/perfil.css
  rails/SISMU/app/assets/stylesheets/productos.css
  rails/SISMU/app/models/client.rb
  rails/SISMU/app/views/artesanos/_form.html.erb
  rails/SISMU/app/views/clients/_form.html.erb
  rails/SISMU/app/views/clients/show.html.erb
  rails/SISMU/app/views/configs/index.html.erb
  rails/SISMU/app/views/devise/registrations/edit.html.erb
  rails/SISMU/app/views/home/index.html.erb
  rails/SISMU/app/views/productos/edit.html.erb
Labels: front-end

#191 agregar campo ref
  rails/SISMU/app/views/productions/_form.html.erb
  rails/SISMU/app/views/productions/_production.html.erb
  rails/SISMU/app/views/productions/index.html.erb
Labels: back-end, front-end
